services:
  postgres:
    image: postgres:17
    container_name: mmotors-postgres
    environment:
      POSTGRES_DB: mmotors_db
      POSTGRES_USER: mmotors_users
      POSTGRES_PASSWORD: mmotors_password
    ports:
      - "5432:5432"
    volumes:
      - mmotors_pg_data:/var/lib/postgresql/data

volumes:
  mmotors_pg_data: